### ISSUE TITLE
Sprint 70 Plan

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#1004]
This plan captures our work for Sprint 70. This is a 2 week iteration.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔵 | more details required
🕐 | waiting for review
🔴 | missing issue reference

## Resource Details
- [ ] 🏃 Rework Resource Details Level page per the new UX design (https://github.com/ManageIQ/manageiq-ui-service/issues/931)

## Service Details

- [ ] ✋ Show details of Generic Objects at the Service Level (https://github.com/ManageIQ/manageiq-ui-service/issues/934) @chalettu 

- [x] 🕐 Created Lifecycle menu (https://github.com/ManageIQ/manageiq-ui-service/pull/912) @chalettu 

## RBAC

- [ ] 🏃 I will see only the options in SUI available for my Role (https://github.com/ManageIQ/manageiq-ui-service/issues/882) @chalettu @AllenBW 

## Usability

- [x] When I duplicate an existing order I want to be able to modify dialog inputs (https://github.com/ManageIQ/manageiq-ui-service/issues/937) @chalettu 
- [x] Create and display a git SHA for the current SUI Build (https://github.com/ManageIQ/manageiq-ui-service/issues/999) @chalettu

**Comment by AllenBW** [comment]
EMOJIIIIIIIIIIIII 💥
