### ISSUE TITLE
"F Release" Plans / Tasking

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#236]
Creating a stub ticket of the things we want to get done for the F release.

**Overall Goals**

- [ ] Rework the UX for the Service Designer for the latest requirements (coming soon)
- [ ] Update the API for the new SD changes
- [ ] Reevaluate the backend for the SD to accomindate the new API / UX changes
- [ ] Evaluate the way we store a "published" blueprint (can we use a common or standard format)
- [ ] Various UX cleanup tasks @serenamarie125 
- [ ] Get Parity Match with Ops UI #145
- [ ] Rework Shopping Cart Experience #239
- [ ] Increase unit test coverage to 100%
- [ ] Setup UI testing, to cover 50% of application

**Tasks (Sprint 51)**

**Tasks (Sprint 52)**

**Tasks (Sprint 53)**

**Tasks (Sprint 54)**

**Tasks (Sprint 55)**

**Comment by chriskacerguis** [comment]
closing this out, we'll do this in PT.
