### ISSUE TITLE
Rework Resource Details Level page per the new UX design

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-ui-service#931]
I want to see most of the details on one page.  We will need to Update Resource page to new UX

<img width="979" alt="screen shot 2017-09-11 at 11 04 01 am" src="https://user-images.githubusercontent.com/2414647/30281889-a2242f62-96e1-11e7-8dfa-1444daec1e80.png">

<img width="628" alt="screen shot 2017-09-11 at 11 54 51 am" src="https://user-images.githubusercontent.com/2414647/30284330-9ef8afa0-96e8-11e7-9def-15d8b97237bd.png">

**ToDo**
- [x] rename vm.details to be resource.details throughout app
- [ ] scaffold basic layout, transfer simple data into new layout
- [ ] add timeline and power state data
- [ ] add system metrics
- [ ] ensure unique url for resource-details state
- [ ] [Aggregate status cards](http://www.patternfly.org/pattern-library/cards/aggregate-status-card/) for 1st row info 
- [ ] info status cards for 1st row info (don't exist in pf)

** Stories Included **
- As a user, I want to see utilisation graph at the top of the Resource Details Level for last 30 days
- As a user, I want to see events at the top of the Resource Details Level for last 1 day

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1497733

**Comment by AllenBW** [comment]
https://github.com/ManageIQ/manageiq-ui-service/pull/920 pr for reference
